#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs tmpfs /run

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

echo "=== ROOTFS INIT STARTED ==="

exec /bin/sh
